const crypto=require('node:crypto');
const useLive=()=>process.env.PAYSTACK_SECRET_KEY?.startsWith('sk_live_')===true;
const expectedDomain=()=>useLive()?'live':'test';
const premiumCommunity=()=>process.env.PREMIUM_COMMUNITY_URL||'https://chat.whatsapp.com/I2WmSKxy1WpEXJCOnEdf7r';
function verifyPaystackSignature(raw,signature){const key=process.env.PAYSTACK_SECRET_KEY;if(!key||!raw||typeof signature!=='string'||!(/^[a-f0-9]{128}$/i).test(signature))return false;return crypto.timingSafeEqual(crypto.createHmac('sha512',key).update(raw).digest(),Buffer.from(signature,'hex'));}
function issueOrder(res,order){const site=new URL(process.env.PUBLIC_SITE_URL);const domain=['www.visoritylive.com','visoritylive.com'].includes(site.hostname)?'; Domain=visoritylive.com':'';res.setHeader('Set-Cookie','visority_order='+encodeURIComponent(sign(order))+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000'+domain+(site.protocol==='https:'?'; Secure':''));}
function isPremiumCharge(t){return t&&t.status==='success'&&t.amount===500000&&t.currency==='NGN'&&t.domain===expectedDomain();}
async function findTransactionByEmail(email){const customer=await paystack('/customer?perPage=100');const match=customer.find?.(c=>c.email?.toLowerCase()===email.toLowerCase());if(!match)return null;const list=await paystack('/transaction?customer='+encodeURIComponent(match.customer_code||match.id)+'&perPage=100&status=success');const hit=list.find?.(isPremiumCharge);if(!hit)return null;const data=await paystack('/transaction/verify/'+encodeURIComponent(hit.reference));return isPremiumCharge(data)&&data.customer?.email?.toLowerCase()===email.toLowerCase()?data:null;}
async function findTransactionByReference(reference){const data=await paystack('/transaction/verify/'+encodeURIComponent(reference));return isPremiumCharge(data)?data:null;}
async function rawBody(req){if(req.body!==undefined){if(!Buffer.isBuffer(req.body)&&typeof req.body!=='string')throw Error('Raw body required');const b=Buffer.from(req.body);if(b.length>100000)throw Error('Too large');return b;}const chunks=[];let size=0;for await(const chunk of req){const b=Buffer.from(chunk);size+=b.length;if(size>100000)throw Error('Too large');chunks.push(b);}return Buffer.concat(chunks);}
const secret=()=>process.env.FUNNEL_SESSION_SECRET;
function sign(data){const p=Buffer.from(JSON.stringify(data)).toString('base64url');return p+'.'+crypto.createHmac('sha256',secret()).update(p).digest('base64url');}
function read(req){try{const c=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('visority_order='));const [p,s]=decodeURIComponent(c.slice(15)).split('.');const expected=crypto.createHmac('sha256',secret()).update(p).digest('base64url');if(s.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(expected)))return null;const d=JSON.parse(Buffer.from(p,'base64url'));return d.exp>Date.now()?d:null;}catch{return null;}}
function json(res,status,data){res.setHeader('Cache-Control','no-store');res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));}
async function body(req){if(req.body)return typeof req.body==='string'?JSON.parse(req.body):req.body;let text='';for await(const chunk of req){text+=chunk;if(text.length>10000)throw Error('Too large');}return JSON.parse(text||'{}');}
async function paystack(path,options={}){const r=await fetch('https://api.paystack.co'+path,{...options,headers:{Authorization:'Bearer '+process.env.PAYSTACK_SECRET_KEY,'Content-Type':'application/json'},signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok||!data.status)throw Error('Payment provider unavailable');return data.data;}
module.exports={sign,read,json,body,paystack,verifyPaystackSignature,issueOrder,isPremiumCharge,expectedDomain,premiumCommunity,findTransactionByEmail,findTransactionByReference,rawBody};

function originAllowed(req){const origin=req.headers.origin;if(!origin)return true;try{const site=new URL(process.env.PUBLIC_SITE_URL).origin;const allowed=new Set([site]);if(['https://www.visoritylive.com','https://visoritylive.com'].includes(site)){allowed.add('https://www.visoritylive.com');allowed.add('https://visoritylive.com');}return allowed.has(origin);}catch{return false;}}
function onlineReady(){try{const site=new URL(process.env.PUBLIC_SITE_URL);return /^sk_(live|test)_\S+$/.test(process.env.PAYSTACK_SECRET_KEY||'')&&(process.env.FUNNEL_SESSION_SECRET||'').length>=32&&(site.protocol==='https:'||(site.protocol==='http:'&&['localhost','127.0.0.1'].includes(site.hostname)));}catch{return false;}}
module.exports.originAllowed=originAllowed;module.exports.onlineReady=onlineReady;
