const crypto=require('node:crypto');
const enabled=()=>!!(process.env.REFERRAL_SHEETS_WEBHOOK_URL&&process.env.REFERRAL_SHARED_SECRET&&process.env.FUNNEL_SESSION_SECRET);
const valid=code=>typeof code==='string'&&/^[a-z0-9][a-z0-9_-]{2,39}$/.test(code)&&!['ambassador','test','preview'].includes(code);
function sign(data){const value=Buffer.from(JSON.stringify(data)).toString('base64url');return value+'.'+crypto.createHmac('sha256',process.env.FUNNEL_SESSION_SECRET).update('referral:'+value).digest('base64url');}
function read(req){try{const cookie=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('visority_referral='));const token=decodeURIComponent(cookie.slice(18));const [value,sig]=token.split('.');const expected=crypto.createHmac('sha256',process.env.FUNNEL_SESSION_SECRET).update('referral:'+value).digest('base64url');if(!sig||sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const data=JSON.parse(Buffer.from(value,'base64url'));return valid(data.code)&&data.exp>Date.now()?data:null;}catch{return null;}}
async function call(action,data){const result=await fetch(process.env.REFERRAL_SHEETS_WEBHOOK_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,secret:process.env.REFERRAL_SHARED_SECRET,...data}),signal:AbortSignal.timeout(7000)});const payload=await result.json();if(!result.ok||!payload.ok)throw Error('Referral storage unavailable');return payload;}
async function capture(req,res,code){const existing=read(req);if(existing)return {captured:true};if(!enabled()||!valid(code))return {captured:false};const result=await call('resolve',{code});if(!result.active)return {captured:false};const data={code,exp:Date.now()+30*86400000};const site=new URL(process.env.PUBLIC_SITE_URL);const domain=['www.visoritylive.com','visoritylive.com'].includes(site.hostname)?'; Domain=visoritylive.com':'';res.setHeader('Set-Cookie','visority_referral='+encodeURIComponent(sign(data))+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000'+domain+(site.protocol==='https:'?'; Secure':''));return {captured:true};}
async function record(kind,data){if(!enabled()||!valid(data.code))return {ok:true,ignored:true};return call('record',{kind,...data});}
module.exports={enabled,valid,read,capture,record};
