const onboarding='https://wa.me/2349037889885?text='+encodeURIComponent("Hello Vee Maji, I’d like to become a Visority ’26 Ambassador. Please help me get started with my official badge, personal referral link and community access.");
const cta=(label)=>`<a class="button button-dark" href="${onboarding}" target="_blank" rel="noopener" data-track="ambassador_whatsapp_click">${label} <span aria-hidden="true">↗</span></a>`;
export function ambassadorPage(){return `<div class="ambassador-v2">
<section class="amb-invitation container" aria-labelledby="amb-title">
<div class="amb-intro"><p class="eyebrow">AMBASSADORSHIP PROGRAM · VISORITY ’26</p><h1 id="amb-title">Become<br>the <em>face.</em></h1><p class="amb-lead">Bring your people into the room.<br>Help shape what happens next.</p><div class="amb-actions">${cta('Become an ambassador')}<a class="amb-text-link" href="#perks">Explore your perks <span aria-hidden="true">↘</span></a></div></div>
<div class="amb-credential-stage"><div class="amb-orbit" aria-hidden="true"></div><div class="amb-credential" aria-label="Visority ambassador badge illustration"><div class="amb-credential-top"><img src="/assets/images/visority-official.webp" alt="Visority ’26" width="100" height="58"><span>THE PEOPLE<br>BEHIND THE ROOM</span></div><div class="amb-seal" aria-hidden="true"><div class="amb-seal-ring"><span>YOUR VOICE</span><span>OUR NEXT CHAPTER</span></div><b>A</b></div><div class="amb-credential-bottom"><span>YOUR PLACE IN THE MOVEMENT</span><strong>Ambassador.</strong><div><span>28–30 OCTOBER 2026</span><span>LIVE ONLINE ↗</span></div></div></div><p class="amb-art-caption">Your voice. A wider circle. More possibility.</p></div>
</section>
<section class="amb-manifesto container" aria-labelledby="amb-mission"><div class="amb-mission-heading"><p class="eyebrow">THE OFFICIAL AMBASSADOR NETWORK</p><h2 id="amb-mission">Don’t just join the room.<br><em>Help build it.</em></h2></div><div class="amb-mission-copy"><p>For the creatives, founders and community leaders who bring people together. Help ambitious African builders discover Visority ’26, and become part of the experience you’re inviting them into.</p><div class="amb-values"><div><span>01</span><h3>Represent the movement.</h3><p>Bring the builders in your circle into a conversation about visibility, value and authority.</p></div><div><span>02</span><h3>Grow with your people.</h3><p>Earn conference access, community connections and recognition through your involvement.</p></div></div></div></section>
<section class="amb-benefits container" id="perks" aria-labelledby="amb-perks-title"><div class="amb-section-heading"><h2 id="amb-perks-title">You bring the people.<br><em>We make it worth it.</em></h2><p>Your place in the programme comes with more than a title.</p></div><div class="amb-perk-grid">${[
['01','Free full access','All three live conference nights, speaker masterclasses, Q&As and networking.','28 / 29 / 30','THREE NIGHTS. ONE EXPERIENCE.'],
['02','Your work in the spotlight','A dedicated ambassador shout-out across Visority’s official social platforms.','YOUR NAME','IN GOOD COMPANY.'],
['03','The inner circle','Private ambassador community access, pre-event briefings and closer connections with the team.','A closer circle.','COMMUNITY BEYOND THE CONFERENCE.'],
['04','Your own referral link','Connect with Vee Maji for your personal link and the programme’s referral milestones.','Your invitation →','A PERSONAL WAY TO BRING PEOPLE IN.']
].map(([n,title,copy,art,caption])=>`<article class="amb-perk amb-perk-${n}"><div class="amb-perk-top"><span>${n}</span><h3>${title}</h3></div><p>${copy}</p><div class="amb-perk-art" aria-hidden="true"><strong>${art}</strong><small>${caption}</small></div></article>`).join('')}</div></section>
<section class="amb-start container" id="get-started" aria-labelledby="amb-start-title"><div class="amb-start-main"><p class="eyebrow">YOUR NEXT STEP</p><h2 id="amb-start-title">Your people.<br>Your influence.<br><em>Your invitation.</em></h2><ol class="amb-steps"><li><strong>Say hello to Vee Maji.</strong><span>Open WhatsApp with your introduction ready to send.</span></li><li><strong>Get set up.</strong><span>The team shares your badge, personal link and programme details.</span></li><li><strong>Bring your circle.</strong><span>Share your invitation and help your community find their place.</span></li></ol>${cta('Get started with Vee Maji')}<p class="amb-small">Ambassador onboarding is separate from paid checkout.</p></div><aside class="amb-share"><span class="amb-share-symbol" aria-hidden="true">↗</span><h3>Good things<br>are better shared.</h3><p>Invite someone now with the public conference link. For a personal referral link, get set up with Vee Maji.</p><label for="ref-link-input">CONFERENCE SHARE LINK</label><div class="ref-row"><input id="ref-link-input" class="ref-input" type="url" value="https://www.visoritylive.com/?ref=ambassador" readonly spellcheck="false"><button class="button button-dark" id="copy-ref" type="button">Copy link ↗</button></div><p id="ref-feedback" role="status" aria-live="polite"></p><p class="amb-share-note">This public link does not assign personal referral credit.</p></aside></section>
</div>`;}
