import {ambassadorPage} from './ambassador-page.mjs';
import {funnelPage,ticket} from './funnel-pages.mjs';
import {renderHomepage} from './homepage.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const canonicalBase=process.env.CANONICAL_SITE_URL||'https://www.visoritylive.com';
const brand=`<a class="wordmark" href="/" aria-label="Visority 26 home"><img src="/assets/images/visority-official.webp" alt="Visority 26" width="100" height="58"></a>`;
const header=`<a class="skip-link" href="#main">Skip to content</a><header class="site-header">${brand}<button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu <span>+</span></button><nav id="main-nav" aria-label="Main navigation"><a href="/#experience">Experience</a><a href="/#speakers">Speakers</a><a href="/#schedule">Schedule</a><a href="/#ambassador-program">Ambassadors</a><a href="/#skill-fund">Skill Fund</a><a href="/partners/" data-track="partner_click">Partner ↗</a><a class="nav-ticket" href="/#pricing">Get your pass <span>↗</span></a></nav></header>`;
const footer=`<footer class="site-footer">${brand}<p>Visibility + Authority.<br>A NextGen Conference experience.</p><div><a href="/partners/" data-track="partner_click">Partner with us ↗</a><a href="/ambassadors/">Become an ambassador ↗</a><a href="/#skill-fund">Skill Fund ↗</a><a href="https://wa.me/2348106535169">Get in touch ↗</a></div><span>© 2026 NEXTGEN</span></footer>`;
const btn=(text,href,style='dark',attrs='')=>`<a class="button button-${style}" href="${href}" ${attrs}>${text} <span>↗</span></a>`;
const eyebrow=t=>`<span class="eyebrow">${t}</span>`;
const top=(a,b)=>`<div class="section-top">${eyebrow(a)}${eyebrow(b)}</div>`;
async function page(path,title,content,scripts=[]){const file=resolve(root,path);await mkdir(dirname(file),{recursive:true});await writeFile(file,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Visority ’26</title><meta name="description" content="Visibility + Authority. Three nights for ambitious African builders. Join Visority ’26 online, 28–30 October 2026, 8pm WAT. Standard is free; Premium is ₦5,000."><meta name="theme-color" content="#290101"><link rel="icon" href="/assets/images/visority-icon.png" type="image/png">
<link rel="canonical" href="${canonicalBase}${path==='index.html'?'/':'/'+path.replace(/index\.html$/,'')}"><link rel="stylesheet" href="/assets/css/fonts.css"><link rel="stylesheet" href="/assets/css/visority.css"><link rel="stylesheet" href="/assets/css/premium.css">${path==='index.html'?'':'<link rel="stylesheet" href="/assets/css/funnel.css"><script src="/assets/js/funnel.js" defer></script>'}${path==='ambassadors/index.html'?'<link rel="stylesheet" href="/assets/css/ambassadors.css">':''}<script src="/assets/js/analytics.js" defer></script><script src="/assets/js/site.js" defer></script>${scripts.map(s=>`<script src="/assets/js/${s}.js" defer></script>`).join('')}</head><body class="${path==='index.html'?'home-page':'support-page'}">${header}<main id="main">${content}</main>${footer}</body></html>`)}
const chapterData=[['01','MIND','Build with audacity.','Move past the fear, hesitation and self-limiting thinking that keeps good work hidden.','mind','↗'],['02','MONEY','Make your work<br>worth more.','Turn your craft into commercial value with better pricing, business structure and sustainable entrepreneurship.','money','<span>VALUE</span><b>↑</b>'],['03','POSITION','Become difficult<br>to overlook.','Build a digital presence and a clear position that open the door to bigger opportunities.','position','<b>YOU</b>'],['04','AUTHORITY','Be the name<br>people trust.','Move beyond being another service provider. Become recognised for what you know and what you do.','authority','✳']];
const speakerData=[['divine','DIVINE','DAY 01 / VISIBILITY','Divine <br>Chukwuemeka','TEDx speaker · Migration researcher<br>Founder, EmigrateEase','Creating Opportunities<br>Through Visibility','divine_chukwuemeka','Divine Chukwuemeka','01'],['mandy','MANDY','DAY 02 / BUSINESS','Mandy <br>Chinedum','Creative director<br>Founder, AmpliQ','The Business Side<br>of Being a Freelancer','mandy_chinedum','Mandy Chinedum','02'],['ikenna','SURPRISE','DAY 03 / AUTHORITY','A special <br>appearance','Identity revealed at the conference','Closing Keynote<br>+ Masterclass','ikenna_okpara','Surprise guest','03']];
const faqs=[['Where is Visority ’26 happening?','Visority ’26 is fully online. Join from wherever you are. The team will share joining instructions with registered attendees before the conference.'],['When do the sessions start?','28, 29 and 30 October 2026, starting at 8pm West Africa Time (WAT, UTC+1) each night.'],['Is the Standard pass really free?','Yes. Standard includes all three live sessions and networking. Premium costs ₦5,000 and adds recordings, session notes, the premium community, priority Q&A, the resource vault and an identity tag.'],['Will I be able to watch the recordings?','Recordings and session notes are included in the Premium pass, so you can revisit the conversations after the event.'],['Who is this experience for?','Founders, creatives, digital entrepreneurs, professionals and emerging leaders who want to turn their work into visibility, commercial value and trusted authority.'],['How will I receive access details?','Provide your email and WhatsApp number when you register so the team can share event updates and joining instructions. For help, contact an Admin on WhatsApp: +234 810 653 5169.']].map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('');
await page('index.html','Building Africa’s Most Wanted Professionals',renderHomepage({btn,eyebrow,chapterData,speakerData,faqs}),['experience']);

const input=(id,label,type='text',extra='')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" ${extra}></div>`;
const choice=(id,values)=>`<div class="choices" data-choice="${id}">${values.map(v=>`<button type="button" class="choice" data-value="${v}" aria-pressed="false">${v}</button>`).join('')}</div><input id="${id}" type="hidden">`;
const steps=[['Let’s start with you.','What should we call you?',input('f-name','Full name','text','autocomplete="name" required maxlength="150"')+input('f-email','Email address','email','autocomplete="email" required maxlength="254"')],['What do you build?','Choose the role that describes you best.',choice('f-role',['Founder','Creative','Digital entrepreneur','Professional / young leader'])],['Stay in the loop.','Add your WhatsApp number so the team can share event updates.',input('f-phone','WhatsApp number, including country code','tel','autocomplete="tel" placeholder="+234 801 234 5678" required maxlength="25"')],['What’s holding you back?','Tell us the main challenge you want to move past.',choice('f-challenge',['Lack of visibility & low market reach','Underpricing & difficulty charging premium','Positioning for global clients','Other'])+'<div id="other-challenge" hidden>'+input('f-challenge-other','Your challenge','text','maxlength="500"')+'</div>'],['What would make this worth it?','Choose what you’re most excited to take away.',choice('f-expect',['Authority and positioning frameworks','A stronger business and pricing approach','Community and networking','Other'])+'<div id="other-expect" hidden>'+input('f-expect-other','Your desired outcome','text','maxlength="500"')+'</div>'],['One more thing.','Have a question for Divine, Mandy or our surprise guest? This one is optional.','<div class="field"><label for="f-note">Your question or note (optional)</label><textarea id="f-note" maxlength="2000" rows="4"></textarea></div>']];
await page('register/index.html','Enter the room',`<section class="subpage"><div class="container registration-ticket-top">${ticket()}</div><div class="container form-layout"><div class="form-sidebar">${eyebrow('YOUR NEXT CHAPTER')}<h1 class="section-title">LET’S GET<br>YOU IN<br><span>THE ROOM.</span></h1><p>Six short steps. A little about you.<br>A lot of possibility ahead.</p><div class="event-mini">VISORITY ’26 / NEXTGEN CONFERENCE<br>28—30 OCTOBER 2026<br>LIVE ONLINE · 8PM WAT</div></div><div class="form-panel"><div class="pass-banner"><strong id="current-pass-name">STANDARD / FREE</strong><a href="/#pricing">Change pass ↗</a></div><div class="form-progress"><div class="progress-meta"><span id="reg-step-label" aria-live="polite">01 — 06</span><span>YOUR PROFILE</span></div><div class="progress-track" role="progressbar" aria-label="Registration progress" aria-valuemin="1" aria-valuemax="6" aria-valuenow="1"><div class="progress-fill"></div></div></div><form id="lead-form" novalidate>${steps.map(([title,desc,fields],i)=>`<section class="form-step" data-step="${i+1}" ${i?'hidden':''}><h2 tabindex="-1">${title}</h2><p>${desc}</p>${fields}</section>`).join('')}<p id="form-error" class="form-error" role="alert" hidden></p><div class="form-actions"><button type="button" class="back-button" id="reg-back" hidden>← Back</button><button type="button" class="button button-dark" id="reg-next">CONTINUE <span>↗</span></button><button type="submit" class="button button-dark" id="reg-submit" hidden>SEND REGISTRATION <span>↗</span></button></div></form><p class="form-note">Your details help us organise your pass and send event updates. Questions? <a href="https://wa.me/2348106535169">Contact the team.</a></p><div id="registration-result" class="status-box" hidden tabindex="-1"><h2>Registration sent.</h2><p>Your next chapter is ready. Taking you to your next step…</p><a id="registration-next" class="button button-dark" href="/access/standard-confirmation/">NEXT STEPS <span>↗</span></a></div></div></div></section>`,['registration']);
await page('partners/index.html','Build the room with us',`<section class="subpage"><div class="container">${eyebrow('PARTNER WITH VISORITY ’26')}<h1 class="section-title">GREAT WORK.<br><span>GREATER TOGETHER.</span></h1><p class="intro">Put your brand alongside ambitious African builders. Help turn fresh thinking into real opportunity.</p><div class="partner-options">${[['ACCESS PARTNER','Open the door.','Sponsor an attendee or make digital skills more accessible.','Access Partner'],['RESOURCE PARTNER','Share what moves us.','Contribute courses, software access or mentorship to a resource library that lasts beyond the conference.','Resource Partner'],['SKILL FUND PARTNER','Invest in the next.','Support training, professional certifications, software subscriptions and mentorship for emerging talent.','Skill Fund Partner']].map(([label,title,desc,type])=>`<article class="partner-option">${eyebrow(label)}<h2>${title}</h2><p>${desc}</p>${btn('LET’S PARTNER','#partner-form','dark',`data-partner-type="${type}"`)}</article>`).join('')}</div><div class="partner-form-wrap">${eyebrow('PARTNERSHIPS & CORPORATE SPONSORSHIP')}<h2>Let’s build something.</h2><p>Tell us about your organisation and what you have in mind. For a corporate sponsorship proposal, choose Corporate Sponsorship below.</p><form id="partner-form" class="form-panel" novalidate>${input('partner-org','Organisation / brand','text','autocomplete="organization" required maxlength="200"')}<div class="field"><label for="partner-type">Partnership type</label><select id="partner-type" required><option value="">Choose a partnership</option>${['Access Partner','Resource Partner','Skill Fund Partner','Corporate Sponsorship','Media Partner','Ecosystem Partner','Other'].map(t=>`<option>${t}</option>`).join('')}</select></div><div class="field"><label for="partner-reach">Community size (optional)</label><select id="partner-reach"><option>Unspecified</option><option>&lt;50</option><option>50-200</option><option>200-500</option><option>500+</option></select></div>${input('partner-contact','Contact email or WhatsApp','text','required maxlength="254"')}<div class="field"><label for="partner-note">What would you like to do together? (optional)</label><textarea id="partner-note" maxlength="2000"></textarea></div><p id="partner-error" class="form-error" hidden role="alert"></p><button class="button button-dark" type="submit">SEND ENQUIRY <span>↗</span></button><p id="partner-result" class="inline-message" role="status" hidden></p></form></div></div></section>`,['partners']);
await page('ambassadors/index.html','Become the Face of Visority ’26',ambassadorPage(),['ambassadors']);
await page('checkout/vip/index.html','Your Premium experience',funnelPage('checkout'),[]);
await page('access/standard-confirmation/index.html','Welcome to the room',funnelPage('standard'),["confirmation"]);
await page('vip/thank-you/index.html','Your Premium access',funnelPage('premium'),["confirmation"]);
await page('access/recover/index.html','Recover your access',funnelPage('recover'),[]);
console.log('Built seven Visority pages.');
await import('./export-site.mjs');

