export function renderHomepage({btn,eyebrow,chapterData,speakerData,faqs}) {
  let firstPhoto=true;
  const photo=(file,alt='',cls='')=>{const priority=firstPhoto;firstPhoto=false;return `<img class="${cls}" src="/assets/images/${file}-960.webp" srcset="/assets/images/${file}-480.webp 480w, /assets/images/${file}-960.webp 960w" sizes="(max-width: 767px) 88vw, 45vw" alt="${alt}" width="896" height="1200" ${priority?'loading="eager"':'loading="lazy"'} decoding="async">`;};
  const bios={divine:'Divine Chukwuemeka is a migration researcher, TEDx speaker and founder of EmigrateEase and Linked On LinkedIn. She holds a first-class degree in History and International Studies from Anchor University and is a Graduate Research Assistant at CEPDeR, Covenant University.',mandy:'Mandy Chinedum is a creative director and founder of AmpliQ. He has led the transformation of over 50 corporate brands and hosts FreelancersOS, whose debut live session reached over 55,000 viewers. His work helps freelancers build sustainable, scalable businesses.',ikenna:'Ikenna Okpara is the founder of CATER Studios and a creative educator. His work focuses on sustainable ecosystems and business infrastructure for African creative innovators.'};
  const learnings={divine:['Make your expertise easier to discover.','Turn a clear digital presence into opportunity.'],mandy:['Connect creative skill to commercial value.','Think more clearly about pricing and business structure.'],ikenna:['Build trust around the work you do.','Make your expertise a lasting professional advantage.']};
  const speakerPanels=speakerData.map(([id,big,day,name,role,topic,img,alt,num])=>`<article class="speaker speaker-${id}" id="speaker-${id}" data-speaker="${id}"><div class="speaker-layout"><div class="speaker-photo">${photo(img,alt)}<span class="portrait-outline" aria-hidden="true"></span></div><div class="speaker-info">${id==='ikenna'?'<span class="special-appearance">✦ SPECIAL APPEARANCE</span>':''}<span class="session-label">${day.replace(' / ',' · ')}</span><h3>${name.replace('<br>','<br>')}</h3><p class="speaker-role">${role}</p>${id==='mandy'?'<div class="speaker-mini-stats"><div><strong>50+</strong><span>BRANDS TRANSFORMED</span></div><div><strong>55K+</strong><span>LIVE VIEWERS</span></div></div>':`<p class="speaker-description">${id==='divine'?'Opening doors through the power of a visible, purposeful professional presence.':'Building the foundations for African creative talent to grow, lead and last.'}</p>`}<div class="speaker-topic"><span>THE CONVERSATION</span><h4>${topic}</h4></div><button type="button" class="speaker-more" data-open-dialog="bio-${id}">Meet ${big.charAt(0)+big.slice(1).toLowerCase()} <span>↗</span></button></div><span class="speaker-index">${num} / 03</span></div></article>`).join('');
  const dialogs=speakerData.map(([id,big,day,name,role,topic,img,alt])=>`<dialog class="speaker-dialog" id="bio-${id}" aria-labelledby="bio-title-${id}"><button type="button" class="dialog-close" data-close-dialog aria-label="Close speaker details">×</button><div class="dialog-portrait">${photo(img,alt)}</div><div class="dialog-copy"><span class="session-label">${day}</span><h2 id="bio-title-${id}">${name.replace('<br>',' ')}</h2><p>${bios[id]}</p><h3>${topic.replace('<br>',' ')}</h3><ul>${learnings[id].map(s=>`<li>${s}</li>`).join('')}</ul><a class="button button-sun" href="/#pricing" data-close-dialog>Choose your pass <span>↗</span></a></div></dialog>`).join('');
  const sessions=[['01','28','VISIBILITY','Be seen.','Creating Opportunities Through Visibility','Divine Chukwuemeka','Build a professional presence that helps the right people discover your work.','divine_chukwuemeka'],['02','29','BUSINESS','Build value.','The Business Side of Being a Freelancer','Mandy Chinedum','Explore the pricing, structure and commercial thinking behind a sustainable creative business.','mandy_chinedum'],['03','30','AUTHORITY','Become the authority.','Closing Keynote + Masterclass','Ikenna Okpara','Connect what you know with the trust, positioning and consistency that make your work stand out.','ikenna_okpara']];
  const marquee='FOUNDERS <i>✳</i> CREATIVES <i>✳</i> PROFESSIONALS <i>✳</i> BUILDERS <i>✳</i> LEADERS <i>✳</i> ';
  firstPhoto=true;
  return `
<section class="hero hero-premium" aria-labelledby="hero-title">
  <div class="hero-inner">
    <div class="hero-copy"><div class="event-label"><span class="live-dot" aria-hidden="true"></span>28–30 OCTOBER 2026 <span class="event-divider"></span> LIVE ONLINE</div><h1 id="hero-title"><span class="hero-line">Building Africa’s</span><span class="hero-line hero-emphasis">most wanted</span><span class="hero-line">professionals<span class="title-dot">.</span></span></h1><p class="hero-description">From overlooked talent to recognised authority. Three nights to rethink your value, sharpen your presence and become known for the work only you can do.</p><div class="hero-actions">${btn('Enter the room','#pricing','sun','data-track="hero_cta_click"')}<a class="hero-secondary" href="#transformation">Explore the transformation <span>↗</span></a></div></div>
    <div class="hero-gallery transformation-scene" aria-label="Visibility plus authority: your next chapter"><div class="scene-caption"><span>A NEW DIMENSION OF YOU</span><span>01 — 03</span></div><div class="scene-sculpture" aria-hidden="true"><div class="portal portal-back"></div><div class="portal portal-middle"></div><div class="portal portal-front"></div><div class="brand-monolith"><div class="monolith-edge"></div><div class="monolith-face"><span class="monolith-edition">THE NEXTGEN CONFERENCE / 2026</span><img src="/assets/images/visority-official.webp" alt="" width="480" height="280"><div class="monolith-rule"></div><span class="monolith-bottom">VISIBILITY<br><b>+ AUTHORITY</b></span><span class="monolith-star">✦</span></div></div><div class="scene-plinth"></div></div><div class="scene-footnote"><span>YOUR TALENT.<br>IN A DIFFERENT LIGHT.</span><span>↗</span></div></div>
  </div>
  <div class="hero-event-bar"><div><strong>A different kind of room.</strong><span>NEXTGEN CONFERENCE · SECOND EDITION</span></div><div class="event-time"><span>28 / 29 / 30 OCT</span><strong>8PM <span>WAT</span></strong></div><a href="#schedule" class="round-link" aria-label="View the three-day schedule">↘</a></div>
</section>
<section class="proof" aria-label="Our previous edition"><div class="proof-intro"><span class="proof-title">The room has a history.</span><p>This October,<br>we go again.</p></div><div class="proof-stat"><strong>500+</strong><span>ATTENDEES IN 2024</span></div><div class="proof-stat"><strong>14</strong><span>COUNTRIES REPRESENTED</span></div><div class="proof-stat"><strong>01</strong><span>PREVIOUS EDITION</span></div></section>
<section id="experience" class="problem section-pad"><div class="container"><div class="problem-stage"><h2 data-reveal>You’re good.<br><span>But are you<br>known?</span></h2><div class="problem-note"><span class="note-mark" aria-hidden="true">↗</span><p>Africa isn’t short of talented builders.</p><p>The problem is how many remain invisible.</p></div></div><div class="problem-lines"><p><span>01</span>Great work without visibility gets overlooked.</p><p><span>02</span>Visibility without authority gets ignored.</p><p><span>03</span>Put them together. Change the equation.</p></div></div></section>
<section class="equation" aria-label="Visibility plus Authority equals Visority"><div class="equation-shell"><span class="equation-orbit" aria-hidden="true"></span><div class="equation-text" data-reveal><span>Visibility</span><span><em>+</em> Authority</span><span class="equation-answer"><em>=</em> Visority.</span></div><p>Not just seen.<br>Recognised for what you bring.</p></div></section>
<section id="transformation" class="transformation section-pad"><span id="about" class="anchor-alias"></span><span id="tracks" class="anchor-alias"></span><div class="container"><div class="transformation-heading"><h2 class="section-title">Good at what you do.<br><span>Ready for what’s next.</span></h2><p>Four shifts that change how you think,<br>build, show up and lead.</p></div><div class="chapter-list">${chapterData.map(([num,label,title,copy,art,symbol])=>`<article class="chapter" data-reveal><div class="chapter-number">${num}<span>/ ${label}</span></div><div class="chapter-copy"><h3>${title}</h3><p>${copy}</p></div><div class="chapter-art ${art}-art" aria-hidden="true">${symbol}</div></article>`).join('')}</div></div></section>
<section class="audience" aria-label="Who Visority is for"><div class="audience-label"><p>Built for people who build.</p><button class="marquee-pause" aria-pressed="false">Pause motion Ⅱ</button></div><div class="marquee"><div class="marquee-track"><span>${marquee}</span><span aria-hidden="true">${marquee}</span></div></div></section>

<section id="ambassador-program" class="ambassador-feature section-pad"><div class="container ambassador-layout"><div class="ambassador-art" aria-hidden="true"><span class="ambassador-art-label">THE PEOPLE WHO MOVE THE ROOM.</span><div class="ambassador-seal"><span>VISORITY ’26</span><b>A</b><span>AMBASSADOR</span></div><div class="ambassador-art-bottom"><span>YOUR VOICE.<br>OUR NEXT CHAPTER.</span><span>↗</span></div></div><div class="ambassador-copy"><span class="section-kicker">THE VISORITY AMBASSADOR PROGRAMME</span><h2 class="section-title">Don’t just<br>join the room.<br><em>Help build it.</em></h2><p>Know people whose work deserves to be seen? Become a Visority ambassador and bring the conference to your community.</p><div class="ambassador-roles"><p><span>01</span>Represent a movement built around African talent.</p><p><span>02</span>Start conversations in your network.</p><p><span>03</span>Invite the builders who need to be in the room.</p></div>${btn('Become an ambassador','/ambassadors/','dark')}<a class="ambassador-contact" href="mailto:nextgencon01@gmail.com?subject=Visority%2026%20ambassador">Questions? Meet the team ↗</a></div></div></section>
<section id="speakers"><div class="container speakers-intro"><span class="section-kicker">THE PEOPLE BEHIND THE PERSPECTIVE</span><h2 class="section-title">Real experience.<br><span>Remarkable people.</span></h2><p>Get closer to the thinking that moves good work forward.</p><nav class="speaker-jump" aria-label="Jump to speaker"><a href="#speaker-divine">Divine Chukwuemeka <span>01</span></a><a href="#speaker-mandy">Mandy Chinedum <span>02</span></a><a href="#speaker-ikenna">Ikenna Okpara <span>✦ SPECIAL APPEARANCE</span></a></nav></div>${speakerPanels}</section>
<section id="schedule" class="schedule section-pad"><div class="container"><div class="schedule-heading"><span class="section-kicker">YOUR THREE-NIGHT JOURNEY</span><h2 class="section-title">Three nights.<br><span>A different trajectory.</span></h2><p>28–30 October 2026. Live online. 8pm WAT each night.</p></div><div class="journey">${sessions.map(([num,date,theme,title,topic,name,desc,img])=>`<details class="session" ${num==='01'?'open':''}><summary><div class="session-date"><strong>${date}</strong><span>OCT / 2026</span></div><div class="session-title"><span class="session-label">DAY ${num} · ${theme}</span><h3>${title}</h3></div><span class="session-time">8PM WAT</span><span class="session-toggle" aria-hidden="true">+</span></summary><div class="session-body"><div class="session-thumb">${photo(img,'')}</div><div class="session-description"><h4>${topic}</h4><p>${desc}</p><span>with ${name}${num==='03'?' · Special appearance':''}</span></div><button type="button" class="calendar-button" data-calendar-day="${num}" data-calendar-title="${topic}">Add to calendar <span>↗</span></button></div></details>`).join('')}</div><p class="schedule-note">Your location doesn’t limit your next move. Join from wherever you’re building.</p></div></section>
<section class="legacy section-pad"><div class="container legacy-layout"><div><span class="section-kicker">NEXTGEN, SINCE 2024</span><h2 class="section-title">We’ve filled<br>the room<br><span>before.</span></h2><p>The first NextGen Conference brought together over 500 attendees across 14 countries. Different paths. A shared ambition to build something that matters.</p><p class="legacy-next">Visority ’26 is the next chapter. <span>↗</span></p></div><div class="legacy-print"><div class="print-top"><span>NEXTGEN<br>CONFERENCE</span><span>THE FIRST<br>CHAPTER</span></div><strong>2024</strong><div class="legacy-lines" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div><div class="print-bottom"><b>500+ PEOPLE.<br>14 COUNTRIES.</b><span>ONE SHARED<br>AMBITION.</span></div></div></div></section>
<section id="pricing" class="pricing section-pad"><div class="container"><div class="pricing-intro"><h2 class="section-title">Your next chapter.<br><span>Your kind of access.</span></h2><p>Be there for the moment. Or take the experience with you.</p></div><div class="ticket-grid"><article class="ticket standard"><div class="ticket-top"><span>STANDARD</span><span class="ticket-symbol" aria-hidden="true">↗</span></div><h3>Free<span>Be there live.</span></h3><p>Three nights of fresh thinking.<br>A room full of possibility.</p><ul><li>All three live conference sessions</li><li>Networking session</li></ul>${btn('Enter free','/register/?pass=standard','dark','data-pass="standard" data-track="standard_selected"')}<small>For the curious. The ambitious. The ready.</small></article><article class="ticket premium"><div class="ticket-top"><span>PREMIUM</span><span class="pill">THE FULL EXPERIENCE</span></div><h3>₦5,000<span>Keep the momentum.</span></h3><p>The conversations, the community<br>and the resources to keep building.</p><ul><li>Everything in Standard</li><li>Session recordings &amp; notes</li><li>Premium community</li><li>Priority Q&amp;A</li><li>Resource vault &amp; identity tag</li></ul>${btn('Go Premium','/register/?pass=premium','sun','data-pass="premium" data-track="premium_selected"')}<small>One pass. More ways to move forward.</small></article></div><details class="pass-comparison"><summary>Compare every benefit <span>+</span></summary><div class="comparison-wrap"><table><caption class="sr-only">Standard and Premium pass benefits</caption><thead><tr><th scope="col">Your experience</th><th scope="col">Standard</th><th scope="col">Premium</th></tr></thead><tbody>${[['Three live sessions',true],['Networking',true],['Recordings and session notes',false],['Premium community',false],['Priority Q&A',false],['Resource vault',false],['Identity tag',false]].map(([benefit,included])=>`<tr><th scope="row">${benefit}</th><td>${included?'Included':'Not included'}</td><td>Included</td></tr>`).join('')}</tbody></table></div></details><p class="ticket-note">Choose your pass. Tell us a little about yourself. You’re one step closer.</p></div></section>
<section id="faq" class="faq section-pad"><div class="container faq-layout"><div><h2 class="section-title">Good<br><span>questions.</span></h2><p>Still have something on your mind?</p><a class="text-link" href="mailto:nextgencon01@gmail.com">Talk to the team <span>↗</span></a></div><div class="faq-list">${faqs}</div></div></section>
<section class="finale"><div class="finale-orbits" aria-hidden="true"><i></i><i></i></div><p>You’ve done the work. Now let them see it.</p><h2>Your work<br>deserves to<br>be <em>seen.</em></h2>${btn('Enter the room','#pricing','sun')}<div class="finale-word" aria-hidden="true">visority ’26</div></section>
<aside class="ticket-dock" aria-label="Quick ticket access" hidden><div><strong>Visority ’26</strong><span>28–30 OCT · ONLINE</span></div><a href="#pricing">Find your pass <span>↗</span></a></aside>
${dialogs}`;
}
